project_name: Bathyx
builds:
  - goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -H=windowsgui
archives:
  - format: binary
nfpms:
  - maintainer: Simaky
    description: Bathyx Project
    homepage: https://github.com/Simaky/Bathyx
    license: MIT
