project_name: Bathyx
builds:
  - flags:
      - -ldflags
      - -H=windowsgui
    goos:
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
nfpms:
  - maintainer: Simaky
    description: Bathyx Project
    homepage: https://github.com/Simaky/Bathyx
    license: MIT
