name: CI

on: [ push, pull_request ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Installing needed Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev portaudio19-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: Test
        run: go test -v ./... -timeout 60s
  linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Installing needed Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev portaudio19-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
